"""empty message

Revision ID: af5f685d5dd8
Revises: 
Create Date: 2020-06-27 13:30:19.673705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5f685d5dd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('instagram_link', sa.String(length=200), nullable=True))
    op.drop_column('artists', 'instagram_page')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('instagram_page', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('artists', 'instagram_link')
    # ### end Alembic commands ###
