"""empty message

Revision ID: b1bb9cd85ee5
Revises: d7062daf175c
Create Date: 2020-06-27 12:22:33.009441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bb9cd85ee5'
down_revision = 'd7062daf175c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('instagram_page', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'instagram_page')
    # ### end Alembic commands ###
